### PR TITLE
Fix "User not connected"

### LINKED ISSUE #62: Stopped working :(
Hi,

I have been using this extension for several years. It was working perfectly fine, but a few weeks ago it suddenly stopped. In the extension bar, instead of the number of notifications, I can only see a gray badge with a question mark inside.

Tested on version 2.8.1, Windows 10 and 11, Opera 99 and 100.

### PR DESCRIPTION
**Pull request by logeen**
- Fix #62
- Additional Polish translation

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -11,7 +11,7 @@
  * Config
  */
 
-const FETCH_URL = 'https://m.facebook.com/';
+const FETCH_URL = 'https://m.facebook.com/home.php';
```
Comment (logeen) [inline src/background.js:14]: I don't know why but it works - no HTTP 301 redirect on this URL
